### ISSUE TITLE
Banner form: 'Message' field shouldn't be expanded.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Wonderwalls#1]
Affected to inner pages 'Contact Us' form also.

![form-01](https://cloud.githubusercontent.com/assets/13309730/13628209/368231fc-e5f6-11e5-94a8-c9a9e6b8e50a.png)

**Comment by euveng** [comment]
Fixed.

**Comment by mahender-sowedane** [comment]
Not fixed

![untitled-1](https://cloud.githubusercontent.com/assets/13309730/13662382/fe40d2f6-e6bf-11e5-8bcf-0e06be019568.png)

**Comment by euveng** [comment]
Sorry about the oversight, fixed.
