### ISSUE TITLE
Banner Section: Images ratio aren't retain, entire width doesn't shown coz images are cut off.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Wonderwalls#117]
Itouch5
![image](https://cloud.githubusercontent.com/assets/13363508/14698651/8bdee91c-07c3-11e6-9c33-caf3f9887679.png)
![image](https://cloud.githubusercontent.com/assets/13363508/14698655/9945803e-07c3-11e6-9c8a-ce9e13ce9ebd.png)
Samsung E7
![image](https://cloud.githubusercontent.com/assets/13363508/14698662/a1cdcb12-07c3-11e6-97dc-6fec42305f44.png)

**Comment by euveng** [comment]
The background image ratio is maintained regardless of image screen, so I'm not sure how you are seeing that the ratio is not maintained. The height is the controlling parameter so that the text doesn't spill over the banner. In doing that, the image width would obviously be more than the screen to maintain the ratio. Will not fix this.

**Comment by maehtitan** [comment]
We are not maintaining the height in the responsive view since it will not achieve the ratio of the image, we make the image max-width  to 100% and position the content below if its too long... Please see sample site here: http://unusualpetvets-tmp.stage.titanweb.com.au/

**Comment by euveng** [comment]
Repositioning the text below the slider is not a good idea because:

1. The text is white and cannot be seen on the white background.
2. We are already moving the contact form below the banner on responsive, if we move more content below the banner, it takes longer for the user to reach the actual content below. Bad idea from UX perspective.
3. Even if this was a legitimate issue, it should have been flagged before, instead of raising other  issues in previous issues that resulted in fixing of that text.
4. Is there a standard for this? This wasn't flagged in other sites anyway eg. http://radlink.stage.titanweb.com.au/

**Comment by maehtitan** [comment]
Answers:
1. The text is white and cannot be seen on the white background.
- **You can use other bg color which blends the site layout or add shadow to the font to make it visible clearly or change font color that matches the preferred color scheme (blue perhaps)**
2. We are already moving the contact form below the banner on responsive, if we move more content below the banner, it takes longer for the user to reach the actual content below. Bad idea from UX perspective.
-**If the text is moved down with the right amount of padding before and after the text it won't require much height. Also it won't take longer for the for the user to scroll since the banner image will be shorter if it resized maintaining its aspect ratio.** 
3. Even if this was a legitimate issue, it should have been flagged before, instead of raising other issues in previous issues that resulted in fixing of that text.
- **That's the purpose of re-checking for some issues are not caught**
4. Is there a standard for this? This wasn't flagged in other sites anyway eg. http://radlink.stage.titanweb.com.au/
-**This is a checking for fully responsive sites.**

**Comment by euveng** [comment]
I have discussed with Jo on this. Considering that there is no responsive design as reference, this subject is open to interpretation.

Jo confirms that Radlink has been done correctly http://radlink.stage.titanweb.com.au/. This is the same with what I have done with Wonderwalls, where the banner text remains in the banner on responsive, instead of being moved below the banner as you suggested. The only difference is that the banner height now needs to be reduced according to the device, thus displaying more of the image width. This fix has been applied, please check.

**Comment by maehtitan** [comment]
**Based from the desktop view of the background image whole width is shown completely.**
![image](https://cloud.githubusercontent.com/assets/13363508/14948028/564a526a-106e-11e6-843c-845208973d8b.png)

**But in mobile view the right side is now hidden. **
![image](https://cloud.githubusercontent.com/assets/13363508/14948030/6e65267c-106e-11e6-8fd4-00cc17905073.png)

Is that considered as fixed completely?

**Comment by euveng** [comment]
Look, it's obvious that the new banner height which you requested will not accommodate the text that you created. Jo and I have discussed that the banner text can be hidden for responsive screen width. We will keep the title and hide the description below 768px. Please confirm.

**Comment by roseliesromeo** [comment]
Okay, I understand your point and as agreed during our call you may hide the banner description.  But make sure that other issues like clipped banner text and the banner image doesn't re-sized accordingly (keeping the full width) are fixed.

**Comment by euveng** [comment]
Thanks @roseliesromeo . Besides the text overflowing the container, are there any other issues pertaining to this ticket?

**Comment by maehtitan** [comment]
Image width still not retain to its aspect ratio.Will close this issue for now, but will make it perfect the next time.

**Comment by euveng** [comment]
On my end I cannot reproduce it. What screen width is it when this occurs?

**Comment by roseliesromeo** [comment]
I thought description will be hidden in lower resolution? We have no problem with it being shown or hidden for as long as it's not clipped. See below screenshot.
![image](https://cloud.githubusercontent.com/assets/11186313/15033828/f4c9b2ac-12a1-11e6-99c3-3b0360e78bc6.png)

**Comment by euveng** [comment]
@roseliesromeo oh I haven't fixed that yet, I would like to have the answer to my question about the wrong image ratio, before fixing the text issue.

**Comment by maehtitan** [comment]
@euveng 

![image](https://cloud.githubusercontent.com/assets/13363508/15034240/0a28e330-12a6-11e6-9e2c-3f323cb23a12.png)

Image full width isn't completely shown. Please observe how the image is being retain in this banner below, no image is being hidden from desktop to 320px view port size.

 sample here: http://unusualpetvets-tmp.stage.titanweb.com.au/


**But if you will still pushed your fixes and its already okay with Joelene with your implementation, so I will marked this one as wontfix. and please proceed to the fixes for the clipped text issue.**

**Comment by euveng** [comment]
@maehtitan Ok, just sharing my thoughts on this. The main priority as we would agree is to maintain the aspect ratio of the image, which in this case is true. 

The sides of the image are somewhat clipped because:
1. The aspect ratio is being maintained.
2. The height is being controlled. If the height is not controlled, and if the client accidentally uploads a very wide image, we will end up with a very short image - making the design look like it's broken. Of course we can specify guidelines for user to follow - but as dev we need to cater for the worst case scenario.

As long as enough of the image is made visible and centred to still deliver the context, some image clipping would be acceptable.

I will now fix the overflowing text issue.

**Comment by euveng** [comment]
Fixed.

**Comment by bernardtitan** [comment]
Hi Ev,

Look, I get both sides of the argument here. @maehtitan Have you asked Jolene about this as I asked you to?

I mention this, because the reason the QAs are being adamant about the banner, is that Jolene herself brought up a site that's being implemented as you're suggesting, and declared that to be unacceptable. Clipping the sides to maintain the aspect ratio in mobile, controlling the height, etc.

Taking that as a precedent, we adjusted our standards here in Cebu to avoid that. Obviously, we also cater for the worst case scenarios here. Hence the following changes:
- Since the banner height will be unreliable due to the requirement of displaying it fully, we cannot keep the text on the banner in mobile devices.
- Banner should be responsive and displayed in full for all resolutions.

This is also why we have the section in the KB Banner entry discussing how to handle full length banners. Please note that it mentions in absolute terms that it should always occupy the full width.
https://knowledgebase.titanweb.com.au/development-2016/development-modules-development-2016/banners

But as it is, if the images are becoming blurry because you're forcing a certain height, that's already a bug if we're going by the images specified in the design.

This is how the sites are being built according to the current standards. An example of a site with banner text: http://aliceclothing-2016.stage.titanweb.com.au/. 

So, if either of you wants to make a special exception for this project from the standards, we need the approval of Jolene. And in doing so, absolve the QA team of any responsibility if ever anybody else down the line flags this as an issue.

Honestly, I'm a bit put-off, I thought this kind of argument died with the Cebu Digital team.

**Comment by euveng** [comment]
Hi all, I have fixed this issue and Jo confirms that this is ok.
