### ISSUE TITLE
Gallery: Images width stretched from 321px - 767px view port size. 

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Wonderwalls#133]
![image](https://cloud.githubusercontent.com/assets/13363508/14772710/ffe91cf2-0ad3-11e6-9277-8aa7200523d5.png)

**Comment by euveng** [comment]
Fixed.

**Comment by maehtitan** [comment]
Not yet fixed. Please refer to this galleries http://luxuride.stage.titanweb.com.au/galleries/, no images which has longer width 
![image](https://cloud.githubusercontent.com/assets/13363508/14949087/9aa12ff0-1079-11e6-89cc-d161e3e574af.png)

**Comment by euveng** [comment]
The image width is set to 100% at 480px which is bootstrap's standard convention. What is it are you expecting instead?

**Comment by maehtitan** [comment]
Just like this one, retain the width and just aligned at the center and doesn't stretched
![image](https://cloud.githubusercontent.com/assets/13363508/14949647/43985378-107e-11e6-97df-f6366b1c3d52.png)

**Comment by euveng** [comment]
I don't agree that the gallery should look like that as it is a waste of real estate on the two sides - this is what old websites would look like. Have a look at http://veracitysolutions.stage.titanweb.com.au/gallery/ and you can see that the images are full width at 479px and below.

**Comment by roseliesromeo** [comment]
Aspect ratio of the images are not maintained on responsive.

**Comment by euveng** [comment]
Done, the image aspect ratios are now fixed at 4:3, but I have maintained full width for the thumbnail.
