### ISSUE TITLE
News: Button text label should be medium and not bold

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Wonderwalls#139]
![image](https://cloud.githubusercontent.com/assets/13363508/14773195/b207cf50-0ad9-11e6-9044-8f80cd39a77e.png)

**Comment by euveng** [comment]
Fixed.

**Comment by maehtitan** [comment]
Still not yet fixed. It is regular and not medium.
![image](https://cloud.githubusercontent.com/assets/13363508/14948242/d32fd3d4-1070-11e6-8f32-11914d95684b.png)

**Comment by euveng** [comment]
I don't understand what the issue is, please rewrite.

**Comment by maehtitan** [comment]
Font-weight 400 is regular, right? and not medium, so I stick to the design coz comparing both of them clearly shown the difference
![image](https://cloud.githubusercontent.com/assets/13363508/14949584/bf6553ee-107d-11e6-8d41-4f866ed10c4f.png)

**Comment by euveng** [comment]
it is generally a bad idea to introduce this many font weight variations. This increases custom font load time by 50%, but since you are insisting on it, I have added this.
