### ISSUE TITLE
Home - Client Testimonials: Broken alignment when added more than two posts.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Wonderwalls#2]
![2016-03-09_1310-hmtesst](https://cloud.githubusercontent.com/assets/13309730/13628544/eebac304-e5f8-11e5-8317-2cf7a62fecdb.png)

**Comment by euveng** [comment]
Fixed

**Comment by mahender-sowedane** [comment]
Not fixed

![2016-03-10_1305-1034](https://cloud.githubusercontent.com/assets/13309730/13662515/1099cce0-e6c1-11e5-940d-2c35fa7732d0.png)

**Comment by euveng** [comment]
What browser is this happening in?

**Comment by euveng** [comment]
Fixed.

**Comment by mahender-sowedane** [comment]
Still affeted on browser reflow at resolution 1001 and so on..
Browser: Firefox

![issue02](https://cloud.githubusercontent.com/assets/13309730/14558704/87364bb8-0321-11e6-8c41-c51ce02aa62a.png)

**Comment by euveng** [comment]
This should be fixed now, please retest.
