### ISSUE TITLE
Inner sidebar & Contact us page: Space gap between form and the Submit button is too small. It should be as per design

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Wonderwalls#22]
Sidebar Contact form

![2016-03-09_1910-001](https://cloud.githubusercontent.com/assets/13309730/13637052/485fe7cc-e62b-11e5-8c25-8a05252429d2.png)

Contact us page

![2016-03-09_1912](https://cloud.githubusercontent.com/assets/13309730/13637060/55561410-e62b-11e5-8c93-462a94f5ad9d.png)

**Comment by euveng** [comment]
Fixed.

**Comment by mahender-sowedane** [comment]
Not fixed

![untitled-1-butnn](https://cloud.githubusercontent.com/assets/13309730/13665134/d90bee1a-e6d0-11e5-8f57-5172f59b986b.png)

**Comment by euveng** [comment]
This is a minor issue (4px), will not fix.
