### ISSUE TITLE
FAQ: Accordion arrow wasn't aligned to the middle. Happens if the FAQ custom post has a long title.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Wonderwalls#39]
![2016-03-10_1926-faq01](https://cloud.githubusercontent.com/assets/13309730/13671449/0e8c3d5e-e6f6-11e5-89c8-f9d8a74fc22e.png)

**Comment by euveng** [comment]
Fixed.

**Comment by mahender-sowedane** [comment]
Not fixed on mobile devices

![screenshot_2016-03-14-15-05-00](https://cloud.githubusercontent.com/assets/13309730/13742149/37e26f36-ea00-11e5-8678-b71cb82dd450.png)

**Comment by euveng** [comment]
Fixed.
