### ISSUE TITLE
Product page: Some of the description is missing and text font-color is not same with design.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Wonderwalls#48]
Affected on About page also

![untitled-1products001](https://cloud.githubusercontent.com/assets/13309730/13675556/2e99aa20-e708-11e5-8344-4f65abfb9d97.png)

**Comment by euveng** [comment]
Fixed .

**Comment by mahender-sowedane** [comment]
Still not fixed as stated in Existing web site.

![untitled-1-fontcolor](https://cloud.githubusercontent.com/assets/13309730/13739900/d8b18486-e9f3-11e5-86a6-29c7f6a088c8.png)

**Comment by euveng** [comment]
The changes are applied on stage and have not been pushed to live yet. All qa fixes/reviews should be completed only on stage before finally pushing to live.

Marking this as fixed.
