### ISSUE TITLE
Home-Our Major Clients: Accordion arrow's are getiing distorted on safari browser

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Wonderwalls#5]
also distorted on small devices.

![untitled-1-issue](https://cloud.githubusercontent.com/assets/13309730/13631749/4c261008-e60c-11e5-8b84-07936aee4c4d.png)

**Comment by euveng** [comment]
Fixed.

**Comment by mahender-sowedane** [comment]
Not fixed

![2016-03-10_1310safari](https://cloud.githubusercontent.com/assets/13309730/13664592/37c4dc30-e6ce-11e5-8167-d81584ab1e15.png)

**Comment by euveng** [comment]
![img_20160311_091810](https://cloud.githubusercontent.com/assets/9030354/13690318/6206856a-e76a-11e5-99cb-506526259a61.jpg)
I believe you need to hard refresh your browser / device to view the changes.
