### ISSUE TITLE
Feedback page: Some of the fields are displaying on devices but disappeared on desktop.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Wonderwalls#65]
But all fields are appeared in website when you inspect the elements. It's getting confusion?

![untitled-1-feedbk](https://cloud.githubusercontent.com/assets/13309730/13745014/b02a2b94-ea11-11e5-976b-230f5c920933.png)

![2016-03-14_1513-formm](https://cloud.githubusercontent.com/assets/13309730/13745038/d1477ce6-ea11-11e5-87f0-40826e7d8867.png)

**Comment by euveng** [comment]
Fixed with #50

**Comment by mahender-sowedane** [comment]
Still not fixed

![untitled-100222](https://cloud.githubusercontent.com/assets/13309730/13773612/2cea4606-eac0-11e5-8e6b-5530ad552f72.png)

**Comment by euveng** [comment]
I'm not sure what you mean by 'active site'. Is it the stage site you're referring to?

**Comment by mahender-sowedane** [comment]
Still issue is not fixed.
Browser : Mozilla, Safari

![feedback](https://cloud.githubusercontent.com/assets/13309730/13977413/cddbd2c6-f0ee-11e5-971f-12847e4c02dd.png)

**Comment by euveng** [comment]
Please reply my question, thanks

**Comment by mahender-sowedane** [comment]
Yes, active site means stage only

**Comment by euveng** [comment]
I've applied a fix which looks ok on all my devices - but please check on your end because I'm not able to reproduce some of the errors.

**Comment by mahender-sowedane** [comment]
Still i'm getting this issue. I have cleared my browser cache and checked. I have checked in others system also. please clear your cache and check it again.

**Comment by euveng** [comment]
Managed to reproduce problem and fixed. Can you retest?
