### ISSUE TITLE
General Pages - Single View: Inner ordered list is not move to the right a bit so that it will identify clearly that it is a inner list

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Wonderwalls#7]
![2016-03-09_1545-enham](https://cloud.githubusercontent.com/assets/13309730/13632517/1887aa32-e610-11e5-9150-c822ae83d613.png)

**Comment by euveng** [comment]
Fixed.

**Comment by mahender-sowedane** [comment]
Still not fixed all pages

![2016-03-10_1426-enh](https://cloud.githubusercontent.com/assets/13309730/13664261/41e52992-e6cc-11e5-92f9-a1df9b9053e9.png)

**Comment by euveng** [comment]
Fixed this on FAQs and Testimonials page - is there anywhere else that needs fixing?
