### ISSUE TITLE
Footer Section: As per Jolene new standard for footer options, TitanWeb should be changed to TitanDigital and also the text and the link.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Wonderwalls#70]
Also give some gap between text and logo as stated in design.

![untitled-1-ftrrr](https://cloud.githubusercontent.com/assets/13309730/13774307/61231430-eac4-11e5-96bf-be2dd4fafdbd.png)

**Comment by euveng** [comment]
Fixed.

**Comment by mahender-sowedane** [comment]
Still Issue is not fixed.
Maintain gap between text and logo as stated in design.

![2016-03-23_1145](https://cloud.githubusercontent.com/assets/13309730/13977290/b5b2ab30-f0ed-11e5-8488-22bd8714d2da.png)

**Comment by euveng** [comment]
Fixed.

**Comment by mahender-sowedane** [comment]
Still not fixed.
![2016-04-04_1409](https://cloud.githubusercontent.com/assets/13309730/14242710/1984fb24-fa6f-11e5-9f44-59512ff49668.png)

**Comment by euveng** [comment]
Fixed. There was an error in the previous update.
