### ISSUE TITLE
News page : W3C errors.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Wonderwalls#78]
https://validator.w3.org/nu/?doc=http%3A%2F%2Fwonderwalls.stage.titanweb.com.au%2Fnews%2F

![w3cnews](https://cloud.githubusercontent.com/assets/13309730/13979581/7376543a-f0ff-11e5-8e95-7c99cc93ce7e.png)

**Comment by euveng** [comment]
Fixed.

**Comment by mahender-sowedane** [comment]
Still not fixed.
https://validator.w3.org/nu/?doc=http%3A%2F%2Fwonderwalls.stage.titanweb.com.au%2Fnews%2F

![showing results for http---wonderwalls stage titanweb com au-news- - nu html checker 2016-04-04 14-07-43](https://cloud.githubusercontent.com/assets/13309730/14242665/dc71d018-fa6e-11e5-87b9-10d018150e0f.png)

**Comment by euveng** [comment]
Fixed. There was an error in the previous update.
