### ISSUE TITLE
Admin : Logo should be resized according to its aspect ratio.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Wonderwalls#79]

**Comment by mahender-sowedane** [comment]
![admin](https://cloud.githubusercontent.com/assets/13309730/13979926/9b520d1c-f101-11e5-9b4b-c5bd50ef4aeb.png)

**Comment by euveng** [comment]
Can the issue be more descriptive? The title and attached image are not comprehensible.

**Comment by mahender-sowedane** [comment]
As per KB articles if images are logos / icons, ensure that it is not cropped and must be re-sized according to its’ aspect ratio.

![2016-04-04_1238](https://cloud.githubusercontent.com/assets/13309730/14242400/5f73a7a8-fa6e-11e5-97a6-ff4a50dc2c68.png)

**Comment by euveng** [comment]
Fixed.

**Comment by mahender-sowedane** [comment]
Still not fixed.

![retaining walls perth - wonder walls 2016-04-06 15-38-05](https://cloud.githubusercontent.com/assets/13309730/14313206/e1307be0-fc0d-11e5-9f12-c8e7245ad208.png)

**Comment by euveng** [comment]
In the latest fix, the logo is constrained by its width. The admin should use fair judgement and expect this behaviour, so they would avoid using a long logo. I feel that this does not need to be constrained by dev and hence will not fix.
