### ISSUE TITLE
Home - Client Testimonials: Post content will cater upto 5 lines only as per scope.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Wonderwalls#8]
Also post title should be single line as per design.

![2016-03-09_1544-testiminls](https://cloud.githubusercontent.com/assets/13309730/13632698/01738b8a-e611-11e5-8293-9f86007d4e6a.png)

**Comment by euveng** [comment]
Fixed.

**Comment by mahender-sowedane** [comment]
Not fixed, also some special symbols displaying unnecessarily.

![2016-03-10_1611-lines](https://cloud.githubusercontent.com/assets/13309730/13667149/10a1f338-e6db-11e5-97d4-dde3c29738bd.png)

**Comment by euveng** [comment]
Performed strip tags to remove tags so all content appears unformatted.
